psRSS=function(a){function w(a,c,f){if(c.addEventListener)c.addEventListener(a,f,!1);else if("load"===a){var b=0;c.onload=c.onreadystatechange=function(){2===++b&&f()}}else c["on"+a]=f}function G(b){a:{var c=n.getElementsByTagName("script");for(var f,g=c.length;g--;)if(~c[g].innerHTML.indexOf("image.providesupport.com")&&c[g].parentElement!==document.head){if(~c[g].innerHTML.indexOf("ps_h\x3d"+a[2])){c=c[g];break a}f=c[g]}c=f}c?c.parentElement.insertBefore(b,c):H.appendChild(b)}function B(a,c,f,g){(c=
g?n.getElementsByClassName(c)[0]:n.getElementById(c))?c!==a&&(c.parentElement.insertBefore(a,c),c.remove()):f(a)}function J(a,c,f){function b(){try{H.removeChild(d)}catch(k){}}var d=r("script");d.type="text/javascript";w("load",d,function(a){c&&c(a);b()});w("error",d,function(a){f&&f(a);b()});d.src=a;H.appendChild(d)}function K(){psRSS(a)}function L(a,c){var b=-1!==c.indexOf("https"),g=c.match(b?/^https?:\/\/([^\/?#]+)(?:[\/?#]|$)/i:/^http?:\/\/([^\/?#]+)(?:[\/?#]|$)/i);g=-1!==c.indexOf("http")?g&&
g[1]:c;var d=2<g.split(".").length?g.split(".")[0]:"";if("vm"===d||"vms"===d||"vm-local"===d||"vm-dev"===d||"vm1-release"===d||"vm2-release"===d||"vm3-release"===d||"vm4-release"===d||""===d||-1===a.indexOf("messenger.")&&-1===a.indexOf("chatapi."))return a;d=-1!==a.indexOf("https")?/^https?:\/\/([^\/?#]+)(?:[\/?#]|$)/i:/^http?:\/\/([^\/?#]+)(?:[\/?#]|$)/i;d=a.match(d);var k=-1!==a.indexOf("http")?d&&d[1]:a;d=2<k.split(".").length?k.split(".")[0]:"";b=-1!==a.indexOf("chatapi")?"https:":b?"https:":
"http:";k=a.replace(b+"//"+k+"/","");return b+"//"+g+"/"+d+"/"+k}function M(a,c,f,g,d){var b=new XMLHttpRequest;b.open(f,a);b.onload=function(){c(JSON.parse(b.responseText))};d&&w("error",b,d);b.send(g)}function W(a){return function(){var c=window.location.pathname,b=window.location.hash;if(c!==N||b!==O)a(c,b),N=c,O=b}}function P(){try{e.localStorage;var a={};return a.s=function(a,b){e.localStorage.setItem(a,b)},a.g=function(a){return e.localStorage.getItem(a)},a.j=function(a){e.localStorage.removeItem(a)},
a}catch(c){return Q}}function C(b){if("function"===typeof x[b])x[b](I,a);else{R=!1;var c=b+"l";if(x[c])x[c][a[2]]||(x[c][a[2]]=K);else{var f={};x[c]=(f[a[2]]=K,f);J(a[23]+"/sjs/mods/"+b+".min.js",function(){for(var a in x[c])x[c][a]()})}}}function S(a){q.init("beforeRender",a);A.r();z.r();T.r();X.r();D.r();q.init("afterRender",a)}var e=window,n=document,H=n.body||n.children[0];a[27]=!1!==a[27];a[28]=a[28]||"bottom:20px;right:20px;";a[29]||a[27]||(a[29]="bottom:20px;right:20px;");a[30]=a[30]||"Open Sans";
a[31]=a[31]||"https://fonts.googleapis.com/css?family\x3dOpen+Sans\x26display\x3dswap";a[51]=a[51]||2147483647;a[52]=!1!==a[52];a[53]=!0===a[53];a[54]=a[54]||0;a[55]=!0===a[55];a[56]=!1!==a[56];a[80]=3===a[0];a[81]=4===a[0];a[82]=~a[1].indexOf("standard");a[83]=~a[1].indexOf("textlink");a[84]=~a[1].indexOf("monitor");a[85]=escape(document.location);if(e["ps"+a[2]])e["ps"+a[2]].render();else{var r=function(a){return n.createElement.call(n,a)},Y=Date.now(),U=function(a,c){return 72E5>Date.now()-Y?setTimeout(a,
1E3*c):null},N=window.location.pathname,O=window.location.hash,u={},Q=(u.s=function(){},u.g=function(){},u.j=function(){},u);a[92]=a[52]?a[53]||!e.JSON?P():function(){function a(a,c,b,f,k,Z,E){E=!1!==E;var p=new Date;p.setTime(p.getTime()+864E5*(b||365));n.cookie=a+"\x3d"+e.encodeURIComponent(c)+"; Expires\x3d"+p.toGMTString()+"; Domain\x3d"+(k?d:f||e.location.host)+"; path\x3d/; SameSite\x3d"+(Z||"Strict")+(g&&E?"; Secure":"")}function c(a){if((a=n.cookie.match(new RegExp("(?:^|; )"+a+"\x3d([^;]*)")))&&
a[1])return e.decodeURIComponent(a[1])}function f(a,c,b){n.cookie=a+"\x3d"+("; Domain\x3d"+(b?d:c||e.location.host))+"; path\x3d/; Max-Age\x3d-99999999; SameSite\x3dStrict"}var g=0===(e.location+"").indexOf("https"),d=function(){for(var b=e.location.hostname.split("."),d=b[b.length-1],g=1;g<b.length;g++)if(d=b[b.length-(g+1)]+"."+d,a("pstc","pstc",1,d),c("pstc"))return f("pstc",d),d;return""}();if(!d)return P();var k={};return k.s=a,k.g=c,k.j=f,k.k=d,k}():Q;a[93]=function(b){function c(a,c){k[a]=
c;e.JSON?b.s(d,JSON.stringify(k),"","",!0):b.s(a,c,"","",!0)}function f(a){return k[a]}function g(a){delete k[a];e.JSON?b.s(d,JSON.stringify(k),"","",!0):b.s(a,"","","",!0)}var d="ps_rvm_"+a[2],k=function(){var a=b.g(d);try{return JSON.parse(a)}catch(l){return{}}}()||{};return{z:c,set:c,y:f,get:f,G:g,remove:g}};a[94]=function(){function a(a){c[a]||(c[a]={x:[],B:0})}var c={},f=[];return{addEventListener:function(b,d){a(b);c[b].x.push(d)},addEventListeners:function(b){for(var d in b)a(d),c[d].x=c[d].x.concat(b[d])},
init:function(a,b){f.push([+new Date,a,b]);if(c[a]){c[a].B++;for(var d=0;d<c[a].x.length;d++)c[a].x[d](b,c[a])}},listeners:c,history:f}};var I={cmdLoad:[function(b){var c=b.C;b=b.A;c!=a[19]&&q.init("isOnlineUpdate",c);D.m(b)}],isOnlineUpdate:[function(b){a[19]=b;z.r();if(a[33]&&v.b())v.b().postMessage('{"name":"reload-sids"}',v.l());else if(window["ps"+a[2]+"um"])window["ps"+a[2]+"um"]()}],chatInvitationConfirm:[function(){e["ps"+a[2]+"ow"](null,!0)}]};a[98]=function(){var b=function(){var b=n.getElementById(a[4]);
b||(b=r("div"),b.id=a[4]);return b}(),c={};return c.e=b,c.h=function(){return b},c.r=function(){B(b,a[4],G)},c.t=function(a){b.appendChild(a)},c};a[96]=function(b){function c(){v.o();return!1}function f(){return!0===a[27]?"z-index:"+a[51]+";position:fixed;"+a[28]:"z-index:"+a[51]+";position:relative;display:inline-block;"}function g(){l||(l=r("a"));l.href="#";l.tabIndex="0";l.className=(a[83]?"text":"chat")+"-button-"+a[2];var b=a[19]?a[48]:a[49];b&&(l.title=b,l.ariaLabel=b);l.onclick=function(){return!1};
w("click",l,c);a[83]?l.innerHTML="\x3cstyle\x3e#sc"+a[2]+" ."+p+" .text-button-"+a[2]+":focus:not(:focus-visible) {outline: 0;}#sc"+a[2]+" ."+p+" .text-button-"+a[2]+':focus-visible { outline: auto; }\x3c/style\x3e\x3cspan id\x3d"ps'+a[2]+'l"\x3e'+(a[19]?a[64]:a[65])+"\x3c/span\x3e":d(b)}function d(b){var c=a[19]?a[59]:a[61],d=a[19]?a[60]:a[62],f=c?Math.round(.7*c)+"px":"auto",g=c?Math.round(.7*d)+"px":"auto";e(a[19]?a[57]:a[58],b,c?c:"auto",d?d:"auto");b="#sc"+a[2]+" ."+p+" .chat-button-"+a[2];c=
"";switch(a[63]){case "hide":c="@media (max-width: 576px) { "+b+" img { display: none !important; } }";break;case "shrink":c="@media (max-width: 576px) { "+b+" img { width: "+f+"; height: "+g+"; } }"}l.innerHTML="\x3cstyle\x3e"+b+":focus:not(:focus-visible) {outline: 0;}"+b+":focus-visible { outline: auto; }"+c+"\x3c/style\x3e";l.appendChild(h)}function e(b,c,d,f){h.name="ps"+a[2]+"image";h.style.display="block";h.style.H="0";h.setAttribute("width",d);h.setAttribute("height",f);c&&(h.alt=c,h.title=
c);h.onload=function(){q.init("messengerToggleContentRendered")};h.src=b}var p="psmtc_"+a[2],l=null,m=function(){var a=n.getElementsByClassName(p)[0];a||(a=r("div"),a.className=p);a.style.cssText=f()+a.style.cssText;return a}(),h=new Image,t={};return t.e=l,t.p=m,t.q=h,t.v=function(){return m},t.w=f,t.r=function(){B(m,p,b.t.bind(b),!0);a[19]||1==a[46]||2==a[46]?(g(),m.appendChild(l),a[83]&&q.init("messengerToggleContentRendered")):3==a[46]&&(m.innerHTML="")},t};a[97]=function(b){var c="psmw_"+a[2],
f=function(){var b=n.getElementsByClassName(c)[0];b||(b=r("div"),b.className=c);b.style.cssText="z-index:"+a[51]+";display:none;position:";""!==a[29]?b.style.cssText+="fixed;"+a[29]:!0===a[27]&&(b.style.cssText+="relative;");return b}(),g={};return g.e=f,g.r=function(){B(f,c,b.t.bind(b),!0)},g};a[95]=function(){function b(){if(e){p=!0;G(d);g();d.style.zIndex=2147483647;var b=r("iframe");b.allowtransparency="true";b.style="background:transparent;width:"+a[14]+";height:"+a[13];b.src=a[15]+"/"+e+"-invitation/"+
a[16]+".html?ps_t\x3d"+Date.now()+"\x26ps_vsid\x3d"+a[3]+"\x26ps_h\x3d"+a[2]+"\x26ps_l\x3d"+escape(n.location)+a[17];b.onload=c;b.frameBorder="no";b.width=a[14];b.height=a[13];b.scrolling="no";d.appendChild(b)}}function c(){p||f();p=!1}function f(){e=d.innerHTML=""}function g(){if(e){var b=Math.round(a[7]),c=1===a[9]?"%":"px",f=1===a[11]?"top":"bottom";d.style[1===a[10]?"left":"right"]=Math.round(a[6])+(1===a[8]?"%":"px");d.style[f]=b+c;1===a[12]&&(d.style.margin="-"+a[13]/2+"px 0 0 -"+a[14]/2+"px")}}
var d=function(){var b=n.getElementById(a[5]);b||(b=r("div"),b.id=a[5]);b.style.cssText="z-index:100;position:fixed";return b}(),e=a[18]?"chat":"",p=!0,l={};return l.r=b,l.m=function(a){a!==e&&(e=a,b())},l.j=f,l.n=g,l};a[99]=function(b){var c="psst_"+a[2],f=function(){var b=r("style");b.id=c;1637703E6<a[54]&&(b.innerHTML+="#sc"+a[2]+",#psmtc_"+a[2]+",#psmtc_"+a[2]+" a,#psmtc_"+a[2]+" img,.ps_cw,.ps_cw p ,.ps_cw div,#ci"+a[2]+"{all:unset}#psmtc_"+a[2]+" a{color:-webkit-link;cursor: pointer;text-decoration: underline}");
return b}(),g={};return g.r=function(){B(f,c,b.t.bind(b))},g};a[91]=function(){var a={};return a.i=function(a){a:{if(y){var b=y.y("pssid");if(b){b=b.split("-");var c=b[0];b=b[1];if(c&&b&&36E5>Date.now()-b)break a}}c=void 0}a=c||a;y.z("pssid",a+"-"+Date.now());return a},a};a[87]=function(b){function c(){null!=k&&(clearTimeout(k),k=null);k=U(c,d);var b=a[23].replace("https:",e.location.protocol)+"/cmd/"+a[24]+".json?ps_t\x3d"+Date.now()+"\x26ps_l\x3d"+escape(n.location)+"\x26ps_r\x3d"+escape(n.referrer)+
"\x26ps_s\x3d"+a[3]+a[25]+a[26];M(b,g,"GET")}function f(b){b=b?a[21]:a[22];d!=b&&(d=b,k=U(c,d))}function g(a){f(a.fastCmd);b({C:a.online,A:a.invite?"chat":""})}var d,k=null;f(a[20]);c();return{F:c}};a[90]=function(b){function c(a,b){J(b,function(){h[a]=window[a];g()},d)}function f(b){if(!a[33]&&!b){try{var c=e.localStorage.getItem(k)}catch(E){c=""}if(c&&(c=JSON.parse(c))&&c.sids&&c.sids.ps_sids&&c.sids.ps_sids.appearanceParams&&15E3>Date.now()-c.timestamp&&c.sids.ps_sids.alm===a[36]&&"leave-message-form"===
c.sids.ps_sids.appearanceParams.screenType^a[19]){h.rvm_s=c.sids;h.isSidsFromcache=!0;g();return}}b='{"companyLogin":"'+a[16]+'","ps_l":"'+a[85]+'","visitorSessionId":"'+a[3]+'","ps_u":"'+a[40]+'"';(c=a[43])&&(b+=',"extraFields":'+c);b+=',"updateStats": '+!n;b+="}";c=L(a[44]+"/"+a[16],a[32]);M(c,function(a){h.rvm_s=a;g();a=JSON.stringify({sids:a,timestamp:Date.now()});try{e.localStorage.setItem(k,a)}catch(ca){}},"POST",b,d)}function g(){if(h.rvm_isLoaded){for(var a=1;4>=a;a++)if(!h["rvm_b"+a])return;
h.rvm_s&&h.rvm_d&&h.rvm_l&&l(h)}}function d(a){console.warn("err",a);h.isCrashed||(h.isCrashed=a,m(h))}var k="sids_"+a[2],n=b.isAutoOpenApp,l=b.D,m=b.E,h={};b={};return b.u=function(b){try{var g=a[40],h=a[41];var k=""!=h?h+"-bundle":"bundle";for(h=1;4>=h;h++)c("rvm_b"+h,g+"/js/"+k+h+".js");c("rvm_l",g+"/languages/"+a[45]+".js");c("rvm_d",L(e["ps"+a[2]+"ds"]?e["ps"+a[2]+"ds"]:a[42],a[32]));f(b);var l=A.e,m=a[30],n=a[31],p=r("link");p.href=n;p.rel="stylesheet";l.appendChild(p);var q=r("p");q.style.cssText=
'opacity:0;position:absolute;font-size:0 !important;z-index:-1;font-family:"'+m+'"';q.innerHTML=".";l.appendChild(q)}catch(aa){d(aa)}},b.f=function(){h.rvm_isLoaded=!0;h.isCrashed?m(h):g()},b};a[89]=function(b){function c(b,c){b?t=b:a[19]||2!=a[46]?t(c):n.location=a[39]}function f(b){var c=V.g("_ga");return a[32]+"/?ps_s\x3d"+a[3]+"\x26ps_l\x3d"+a[85]+"\x26ps_h\x3d"+a[2]+"\x26chash\x3d"+a[16]+"\x26ps_ssu\x3d"+window.encodeURIComponent(p?!0:!F)+"\x26ps_f\x3d"+window.encodeURIComponent(a[30])+"\x26ps_fu\x3d"+
window.encodeURIComponent(a[31])+"\x26ps_lfb\x3dtrue\x26ps_ao\x3d"+!!l+(b?"\x26ps_fci\x3dtrue":"")+(c?"\x26_ga\x3d"+c:"")+a[26]}function g(a){a.isAutoOpenApp=l;m.postMessage(JSON.stringify({name:"data-for-rvm",data:a}),"*")}function d(b){m=r("iframe");m.name="ifm"+a[2];m.setAttribute("allowfullscreen","");m.src=f(b);m.style.cssText="display:none";T.e.appendChild(m);m=m.contentWindow}function k(){var b=r("script");b.className="psms_"+a[2];b.type="text/javascript";G(b);b.src=a[35]+"?chash\x3d"+a[16]+
"\x26ps_vsid\x3d"+a[3]+"\x26ps_alm\x3d"+a[36]+"\x26ps_re\x3d"+F+"\x26ps_mo\x3d"+p+"\x26ps_ao\x3d"+!!l+"\x26ps_font\x3d"+a[30]+"\x26ps_ecp\x3d"+encodeURIComponent(JSON.stringify(a[38]))+"\x26"+a[36]+"\x26isShowChatButtonAfterOpenChat\x3d"+a[55]+"\x26buttonLocation\x3d"+encodeURIComponent(a[28])+"\x26messengerLocation\x3d"+encodeURIComponent(a[29])}var p=(b=+b.y("mo"))&&3E5>Date.now()-b,l=!a[33]&&(p||F)&&!(!a[19]&&2==a[46]),m=null,h=a[90]({D:function(a){g(a)},E:function(a){h[rvm_isLoaded]&&g(a)},isAutoOpenApp:l}),
t=function(){return a[33]?function(b){if(m&&!m.closed)m.focus();else{var c=a[34].split(","),d=parseInt(c[0].replace("width\x3d",""));c=parseInt(c[1].replace("height\x3d",""));d="menubar\x3d0,location\x3d0,scrollbars\x3dauto,resizable\x3d1,status\x3d0,"+a[34]+",left\x3d"+(n.documentElement.clientWidth-d)/2+"px,top\x3d"+(n.documentElement.clientHeight-c)/2+"px";h.u(b);m=e.open(f(b),"pscw_"+Date.now(),d);a[56]||(z.e.style.cssText+="display: none;")}q.init("chatOpen")}:function(b){e.ps_rvm_cur_scr?setTimeout(t,
100):(h.u(b),d(b),e.ps_rvm_cur_scr=a[2],c(function(){}),k(),q.init("chatOpen"))}}();l&&t();b={};return b.a=l,b.o=function(){c()},b.c=c,b.d=h,b.b=function(){return m},b.l=f,b};e.psmods=e.psmods||{};var x=e.psmods,R=!0;a[81]&&a[47]&&C("rvmShowPoweredBy");a[84]&&C("monitor");a[80]&&C("classicBanner");a[38].enabled&&a[19]&&!F&&!a[84]&&C("eyeCatcher");x.customMod&&x.customMod(I,a);if(R){e.psBanner=e["ps"+a[2]]={params:a};var V=a[92],y=a[93](V);e.psBanner.cacherWorker=y;var q=a[94]();e.psBanner.events=
q;q.addEventListeners(e["ps"+a[2]+"listeners"]);q.addEventListeners(I);q.init("servicesLoad");var F=!!y.get("re");u=y.get("last-visit");u=!u||3E5<Date.now()-u;e.psBanner.isNewVisit=u;u=a[91]();a[3]=u.i(a[3]);var A=a[98]();e.psBanner.rootElement=A;var z=a[96](A);e.psBanner.messengerToggle=z;var T=a[97](A),X=a[99](A),D=a[95]();S(!0);e.psBanner.render=S;var ba=a[87](function(a){q.init("cmdLoad",a)}),v=a[89](y);(function(){w("pagehide",e,function(){y.z("last-visit",JSON.stringify(Date.now()))});w("message",
e,function(b){b.data&&"string"===typeof b.data&&(b.data=="rvm oc "+a[2]?q.init("chatInvitationConfirm"):b.data=="rvm-is-loaded-"+a[2]?v.d.f():~b.data.indexOf("rvm-beforeunload")&&a[33]&&!a[56]&&(z.e.style.cssText=z.e.style.cssText.replace("display: none;","")))});w("resize",e,D.n);w("scroll",e,D.n);var b=W(ba.F);w("popstate",e,b);w("hashchange",e,b);var c=history.pushState;history.pushState=function(){c.apply(this,arguments);b()};var f=history.replaceState;history.replaceState=function(){f.apply(this,
arguments);b()}})();v.a&&v.o();e.psOpenWindow=function(a){if(e["ps"+a+"ow"])e["ps"+a+"ow"]();else v.c()};e["ps"+a[2]+"ow"]=v.c.bind(v);e.psBanner.open=v.c}}};if(window.psPDSS)for(pl=psPDSS.length;pl--;)psRSS(psPDSS[pl]);